name = "imgauth"
main = "/worker/worker.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[site]
bucket = ""

[build]
command = ""

[[rules]]
type = "PythonWorker"
globs = ["**/*.py"]
fallthrough = true